name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - name: Build
      - uses: actions/checkout@v3
      - run: |
          python3 -m build
          python3 -m venv testenv
          source testenv/bin/activate
          pip uninstall -y threadsnake || true
          dir dist/*.whl | xargs -I {} pip install {}
          pip install requests
          pip install pytest
          pytest
          deactivate