name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
      - run: |
          python3 -m build

      - run: |
          python3 -m venv testenv
          source testenv/bin/activate
          dir dist/*.whl | xargs -I {} pip install {}
          pip install requests
          pip install pytest
          python3 tests/test_server/main.py
          deactivate