name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
      - run: |
          rm -r dist
          python3 -m build
          pip3 uninstall -y threadsnake
          dir dist/*.whl | xargs -I {} pip3 install {}
          pytest