name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ready
          python3 builder.py CLEAN_DIST
          python3 builder.py LOAD_VERSION GENERATE_FILES
          python3 builder.py BUILD
          python3 builder.py INSTALL