name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo [pypi] > .pipyrc
          echo username = __token__ >> .pipyrc
          echo password = ${{ secrets.PYPI_UPLOAD_TWINE_TOKEN }} >> .pipyrc
          python3 builder.py CLEAN_DIST LOAD_VERSION GENERATE_FILES BUILD INSTALL