name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
      - run: |
          py -m build
#          twine upload -u __token__ -p ${{ secrets.PYPI_UPLOAD_TWINE_TOKEN }} dist/*